-- =========================
-- ENUMS
-- =========================
CREATE TYPE tipo_cliente AS ENUM ('cliente', 'proveedor');
CREATE TYPE tipo_movimiento AS ENUM ('ingreso', 'salida', 'devolucion');

-- =========================
-- USERS
-- =========================
CREATE TABLE users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);

-- =========================
-- PERSONAS
-- =========================
CREATE TABLE personas (
  id SERIAL PRIMARY KEY,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  user_id INT UNIQUE,
  fecha_nacimiento DATE,
  genero VARCHAR(20),
  telefono VARCHAR(20),
  direccion TEXT,
  nacionalidad VARCHAR(50) NOT NULL
);

ALTER TABLE personas
ADD CONSTRAINT fk_persona_user
FOREIGN KEY (user_id) REFERENCES users(id);

-- =========================
-- ROLES
-- =========================
CREATE TABLE roles (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT
);

-- =========================
-- PERMISOS
-- =========================
CREATE TABLE permisos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  resource VARCHAR(100),
  action VARCHAR(100) NOT NULL
);

-- =========================
-- ROLE_USER
-- =========================
CREATE TABLE role_user (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INT NOT NULL,
  role_id INT NOT NULL,
  CONSTRAINT fk_role_user_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_role_user_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- =========================
-- PERMISO_ROLE
-- =========================
CREATE TABLE permiso_role (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  permiso_id INT NOT NULL,
  role_id INT NOT NULL,
  CONSTRAINT fk_permiso_role_permiso FOREIGN KEY (permiso_id) REFERENCES permisos(id),
  CONSTRAINT fk_permiso_role_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- =========================
-- SUCURSALES
-- =========================
CREATE TABLE sucursales (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  direccion TEXT NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  ciudad VARCHAR(50) NOT NULL
);

-- =========================
-- SUCURSAL_USER
-- =========================
CREATE TABLE sucursal_user (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id INT NOT NULL,
  user_id INT NOT NULL,
  CONSTRAINT fk_sucursal_user_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id),
  CONSTRAINT fk_sucursal_user_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =========================
-- ALMACENES
-- =========================
CREATE TABLE almacenes (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  codigo VARCHAR(20),
  descripcion TEXT,
  direccion TEXT NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  ciudad VARCHAR(50) NOT NULL,
  sucursal_id INT NOT NULL,
  CONSTRAINT fk_almacen_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(id)
);

-- =========================
-- CATEGORIAS
-- =========================
CREATE TABLE categorias (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL,
  descripcion TEXT
);

-- =========================
-- PRODUCTOS
-- =========================
CREATE TABLE productos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(200) NOT NULL,
  descripcion TEXT,
  unidad_medida VARCHAR(20),
  marca VARCHAR(100),
  precio_venta_actual DECIMAL(12,2) NOT NULL,
  imagen VARCHAR(255),
  estado BOOLEAN NOT NULL,
  categoria_id INT NOT NULL,
  CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(id)
);

-- =========================
-- ALMACEN_PRODUCTO
-- =========================
CREATE TABLE almacen_producto (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cantidad_actual INT NOT NULL,
  fecha_actualizacion DATE,
  unidad_medida VARCHAR(20),
  marca VARCHAR(100),
  precio_venta_actual DECIMAL(12,2) NOT NULL,
  imagen VARCHAR(255),
  estado BOOLEAN NOT NULL,
  producto_id INT NOT NULL,
  almacen_id INT NOT NULL,
  CONSTRAINT fk_almacen_producto_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
  CONSTRAINT fk_almacen_producto_almacen FOREIGN KEY (almacen_id) REFERENCES almacenes(id)
);

-- =========================
-- CLIENTE_PROVEEDOR
-- =========================
CREATE TABLE cliente_proveedor (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo tipo_cliente NOT NULL,
  razon_social VARCHAR(200),
  nro_identificacion VARCHAR(100),
  telefono VARCHAR(20),
  direccion TEXT,
  correo VARCHAR(255),
  estado BOOLEAN NOT NULL
);

-- =========================
-- NOTAS
-- =========================
CREATE TABLE notas (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha DATE NOT NULL,
  tipo_nota VARCHAR(30),
  impuestos DECIMAL(13,2),
  descuentos DECIMAL(13,2),
  estado_nota VARCHAR(50) NOT NULL,
  observaciones TEXT,
  user_id INT NOT NULL,
  cliente_proveedor_id INT NOT NULL,
  CONSTRAINT fk_nota_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_nota_cliente FOREIGN KEY (cliente_proveedor_id) REFERENCES cliente_proveedor(id)
);

-- =========================
-- MOVIMIENTOS
-- =========================
CREATE TABLE movimientos (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nota_id INT NOT NULL,
  producto_id INT NOT NULL,
  almacen_id INT NOT NULL,
  cantidad INT NOT NULL,
  tipo_movimiento tipo_movimiento NOT NULL,
  precio_unitario_compra DECIMAL(13,2) NOT NULL,
  precio_unitario_venta DECIMAL(13,2) NOT NULL,
  observaciones TEXT,
  CONSTRAINT fk_movimiento_nota FOREIGN KEY (nota_id) REFERENCES notas(id),
  CONSTRAINT fk_movimiento_producto FOREIGN KEY (producto_id) REFERENCES productos(id),
  CONSTRAINT fk_movimiento_almacen FOREIGN KEY (almacen_id) REFERENCES almacenes(id)
);

-- =========================
-- COMMENTS
-- =========================
COMMENT ON COLUMN cliente_proveedor.tipo IS 'cliente | proveedor';
COMMENT ON COLUMN movimientos.tipo_movimiento IS 'ingreso | salida | devolucion';
